### ISSUE TITLE
Can I buy you a game?

### ISSUE THREAD

**Issue by sheodox** [Idearum/NieRAutomata_Inventory_Editor#2]
I used this to give myself a Powerup Part S so I could upgrade the last pod for the achievement because something was glitched and I couldn't get the third one. This tool saved having to redo ~60 hours of play time for the achievement! Thank you so much!

**Comment by Aemony** [comment]
I'm happy to hear that the tool helped you! :) You don't have to buy me a game, but if you really want to then you can add me on Steam and gift me whatever you want: https://steamcommunity.com/id/aemony/
